### ISSUE TITLE
build.json file is empty

### ISSUE THREAD

**Issue by natewoodbridge** [WeareJH/config-gen#24]
Hey,
Using the default config in the README, I get an empty build.json file.

I might being a bit too keen, or if I have not followed the instructions correctly - I know you are going to add some demo code.

Thanks!

I have a file `public_html/config-gen.yml`:
```yml
presets:
  - name: m2
    options:
      bundle_config: file:test/fixtures/bundle-config.yml
```

And `public_html/test/fixtures/bundle-config.yml`:
```yml
bundles:
  - name: "bundles/main"
    urls:
      - "/"
    children:
      - name: "bundles/product"
        urls:
          - "/test-bracelet/"
        children: []
```

But when I try and visit (after visiting `https://127.0.0.1:8080/` once) `https://127.0.0.1:8080/__bs/build.json` gives me this:
```json
{
  "generateSourceMaps": true,
  "inline_text": true,
  "optimize": "none",
  "deps": [],
  "map": {},
  "config": {},
  "shim": {},
  "paths": {},
  "modules": [
    {
      "name": "requirejs/require",
      "include": [],
      "exclude": [],
      "create": false
    },
    {
      "name": "bundles/main",
      "include": [],
      "exclude": [
        "requirejs/require"
      ],
      "create": true
    },
    {
      "name": "bundles/product",
      "include": [],
      "exclude": [
        "requirejs/require",
        "bundles/main"
      ],
      "create": true
    }
  ]
}
```
