### ISSUE TITLE
actix_web pipeline error - 502 - Too many open files

### ISSUE THREAD

**Issue by Januszpl** [WeareJH/config-gen#44]
When experimenting with different bundle-config.yml I was editing config and browsing website. Then suddenly I got empty build.json and I noticed that I had serveral errors like this one:
```
ERROR 2018-11-21T01:21:50Z: actix_web::pipeline: Error occured during request handling, status: 502 Bad Gateway Failed to connect to host: Too many open files (os error 24)
```

and then:

```
thread 'arbiter:2fed453f-22f1-4ccf-b941-935d1a843a2b:actix-net-worker-0' panicked at 'can read current dir: Os { code: 24, kind: Other, message: "Too many open files" }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
ERROR 2018-11-21T01:21:50Z: actix_net::server::accept: No workers
ERROR 2018-11-21T01:21:50Z: actix_net::server::server: Worker has died 0, restarting
```

Adding this ticket for further investigating.

My config during this error was on custom project
```
bundles:
  - name: "bundles/simple-page"
    urls:
      - "/o-nas"
    children:
      - name: "bundles/cms-page"
        urls:
        - "/kontakt"
        children:
          - name: "bundles/category"
            urls:
              - "/meskie/odziez/spodnie"
              - "/search/result/?q=spodnie"
            children: []
          - name: "bundles/homepage"
            urls:
              - "/"
            children: []
          - name: "bundles/product"
            urls:
              - "/spodnie-1"
            children: []
          - name: "bundles/cart"
            urls:
              - "/checkout/cart"
              - "/checkout/cart/"
            children: []
          - name: "customer-account"
            urls:
              - "customer/account/login/"
              - "/customer/account/index/"
              - "/customer/account/index"
              - "/customer/account/edit"
              - "/customer/account/edit/"
              - "sales/order/view/order_id/121/"
              - "/customer/address/new/"
              - "/sales/order/history/"
              - "/aw_rma/customer/"
              - "/wishlist"
            children: []
          - name: "club"
            urls:
              - "/club"
            children: []
  - name: "bundles/checkout"
    urls:
      - "/checkout"
      - "/checkout/"
      - "/checkout/#payment"
    children: []
```
