### ISSUE TITLE
actix_web::pipeline: Error occurred during request handling: err

### ISSUE THREAD

**Issue by drazulay** [WeareJH/config-gen#50]
Upon first navigating to a slug belonging to a bundle registered in bundle-config.yml in order to build configuration for it, I get the following messages in the terminal:
```
ERROR 2019-08-29T09:47:56Z: actix_web::pipeline: Error occurred during request handling: err
ERROR 2019-08-29T09:47:56Z: actix_web::server::h2: Unhandled error: err
```
After which no changes are reflected at the endpoints for build.js, seed.js, etc.

This is what my config looks like:
```
bundles:
  - name: "bundles/main"
    urls:
      - "/"
    children:
      - name: "bundles/product"
        urls:
          - "/index.php/test-product"
        children: []
      - name: "bundles/category"
        urls:
          - "/index.php/test-category"
        children: []
      - name: "bundles/checkout"
        urls:
          - "/index.php/checkout"
        children: []
```
